### ISSUE TITLE
Quick question regarding IEmod files

### ISSUE THREAD

**Issue by Irithyl** [GregRos/IEMod.pw#83]
Hi! I just download the 5.1 beta launcher and the 5.2.1 patch dll. My question is, where do I put the patch dll? I copied the ie mod folder to my managed, then clicked on patchwork launcher but there I can only see the iemod.pw.dll file and not the iemod.dll. :s I don't have a clue how this works.

**Comment by Irithyl** [comment]
Also, when I test run I get an error and the following text report:

016-03-08 00:11:47.790 +00:00 [Error] The patch located in D:\Programs\Steam\steamapps\common\Pillars of Eternity\ie mod\Mods\IEMod.dll could not be loaded.
Patchwork.PatchDeclerationException: The patch did not have a PatchInfo class.
   at PatchworkLauncher.LaunchManager.Command_Direct_AddPatch(String path, Boolean isEnabled)
2016-03-08 00:11:47.810 +00:00 [Error] An error has occurred,
While trying to: Load a patch
Error type: A patch was invalid, incompatible, or caused an error. (PatchDeclerationException)
Internal message: The patch did not have a PatchInfo class.
Object(s) that failed: D:Programs...\Mods\IEMod.dll

Patchwork.PatchDeclerationException: The patch did not have a PatchInfo class.
   at PatchworkLauncher.LaunchManager.Command_Direct_AddPatch(String path, Boolean isEnabled)
   at PatchworkLauncher.LaunchManager.Command_Dialog_AddPatch(IWin32Window owner)
2016-03-08 00:11:59.970 +00:00 [Information] Created patcher for assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-03-08 00:12:00.172 +00:00 [Information] Implicitly creating type for: <PrivateImplementationDetails>.
2016-03-08 00:12:00.173 +00:00 [Warning] Conflict between types: <PrivateImplementationDetails>, and <PrivateImplementationDetails>.
2016-03-08 00:12:00.174 +00:00 [Warning] The type called <PrivateImplementationDetails> was to be introduced under the name <PrivateImplementationDetails> but will be introduced under the name <PrivateImplementationDetails>_$pw$_u159X
2016-03-08 00:12:00.174 +00:00 [Information] Implicitly creating type for: IEMod.QuickControls.BindingValue/<>c__DisplayClass0_0`1.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.QuickControls.BindingValue/<>c__DisplayClass2_0`1.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.QuickControls.BindingValue/<>c__DisplayClass3_0`1.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.QuickControls.QuickButton/<>c.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.QuickControls.QuickDropdown`1/<>c__DisplayClass25_0.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.QuickControls.Behaviors.BlockClicking/<>c__0`1.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Mods.Options.IEModOptions/<>c.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Mods.Options.mod_UIOptionsManager/<>c.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Mods.UICustomization.UICustomizer/<>c.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Mods.DropButtonMod.DropButton/<>c.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Mods.BonusSpellsGrimoire.mod_Grimoire/<>c.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.StringHelper/<>c__DisplayClass0_0.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.MemberAccess`1/<>c__DisplayClass17_0.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.ReflectHelper/<>c__DisplayClass2_0.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.ReflectHelper/<>c__DisplayClass2_1.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.ReflectHelper/<>c__DisplayClass2_2.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.ReflectHelper/<>c__DisplayClass3_0`1.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.ReflectHelper/<>c__DisplayClass4_0`1.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.ReflectHelper/<>c__DisplayClass8_0.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.ReflectHelper/<>c__DisplayClass8_1.
2016-03-08 00:12:00.188 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.ReflectHelper/<>c__DisplayClass8_2.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.ReflectHelper/<>c.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.IEControlFactory/<>c__DisplayClass7_0`1.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.IEControlFactory/<>c__DisplayClass9_0.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.UnityPrinter/<>c.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.ControlHelper/<>c__DisplayClass0_0.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.UnityObjectExtensions/<>c__DisplayClass2_0`1.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.UnityObjectExtensions/<>c__DisplayClass20_0.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.UnityObjectExtensions/<>c__DisplayClass25_0.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.UnityObjectExtensions/<>c.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.UnityObjectExtensions/<>c__DisplayClass26_0.
2016-03-08 00:12:00.189 +00:00 [Information] Implicitly creating type for: <PrivateImplementationDetails>/__StaticArrayInitTypeSize=36.
2016-03-08 00:12:00.190 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.UnityPrinter/RecursiveObjectPrinter/<>c__DisplayClass5_0.
2016-03-08 00:12:00.190 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.UnityPrinter/RecursiveObjectPrinter/<>c__DisplayClass5_1.
2016-03-08 00:12:00.190 +00:00 [Information] Implicitly creating type for: IEMod.Helpers.UnityPrinter/RecursiveObjectPrinter/<>c__DisplayClass5_2.
2016-03-08 00:12:00.205 +00:00 [Information] Implicitly creating method for: Void mod_UIOptionsManager::<mod_Start>b__28_1(IBindingValue`1<System.Boolean>).
2016-03-08 00:12:00.205 +00:00 [Information] Implicitly creating method for: Void mod_UIOptionsManager::<mod_Start>b__28_2(IBindingValue`1<System.Boolean>).
2016-03-08 00:12:00.206 +00:00 [Information] Implicitly creating method for: Boolean mod_UIPartyPortrait::get_IsVertical().
2016-03-08 00:12:00.206 +00:00 [Information] Implicitly creating method for: Void mod_UIPartyPortrait::set_IsVertical(Boolean).
2016-03-08 00:12:00.206 +00:00 [Information] Implicitly creating method for: AbilityActionData mod_GameResources::get_AbilityActionData().
2016-03-08 00:12:00.702 +00:00 [Information] Clearing fields in UIOptionsManager/OptionsPage
2016-03-08 00:12:00.703 +00:00 [Information] =====Creating new fields=====
2016-03-08 00:12:01.852 +00:00 [Error] An error has occurred,
While trying to: Patch the game
Error type: A system error or some sort of bug. (NullReferenceException)
Internal message: Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Patchwork.AssemblyPatcher.FixFieldReference(FieldReference yourFieldRef)
   at Patchwork.AssemblyPatcher.TransferMethodBody(MethodDefinition targetMethod, MethodDefinition yourMethod)
   at Patchwork.AssemblyPatcher.ModifyMethod(TypeDefinition targetType, MethodDefinition yourMethod, MemberActionAttribute memberAction, MethodDefinition targetMethod)
   at Patchwork.AssemblyPatcher.UpdateMethods(SimpleTypeLookup`1 methodActions)
   at Patchwork.AssemblyPatcher.PatchManifest(PatchingManifest manifest, ProgressObject o)
   at PatchworkLauncher.LaunchManager.ApplyInstructions(IEnumerable`1 patchGroups, ProgressObject po)
   at PatchworkLauncher.LaunchManager.<>c__DisplayClass46_0.<Command_Patch>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PatchworkLauncher.LaunchManager.<Command_Patch>d__46.MoveNext()

**Comment by tjayharvey** [comment]
I zipped the wrong file. Will correct in a minute.

**Comment by Irithyl** [comment]
Oh, I tried it the new file and got this:

Error] The patch located in D:\Programs\Steam\steamapps\common\Pillars of Eternity\ie mod\Mods\IEMod.dll could not be loaded.
Patchwork.PatchDeclerationException: The patch did not have a PatchInfo class.
   at PatchworkLauncher.LaunchManager.Command_Direct_AddPatch(String path, Boolean isEnabled)
2016-03-08 00:11:47.810 +00:00 [Error] An error has occurred,
While trying to: Load a patch
Error type: A patch was invalid, incompatible, or caused an error. (PatchDeclerationException)
Internal message: The patch did not have a PatchInfo class.
Object(s) that failed: D:Programs...\Mods\IEMod.dll

...

The report file is much much bigger, am I doing something wrong?

**Comment by tjayharvey** [comment]
You probably need to adjust your active mods back to IEMod.pw.dll.

**Comment by Alakabon** [comment]
Mine works fine with that file... Have you tried deleting the Assembly-CSharp.dll.pw.modified file from the Managed folder ? This will cause Patchwork to... re-patch and will override what you had previously.

**Comment by Irithyl** [comment]
What do you mean? I'll explain what I am doing. I download 5.1.0-beta Launcher for 2.03.0788 ZIP and  5.2.1 Patch DLL ZIP, I copied the iemod folder to Managed and also put in Managed the 5.2.1 patch dll zip file. Then I ran the patchwork launcher and chose that dll file. When I tested it I got that report I pasted here :S Oh!  Just read what Alakabon wrote, Im going to try it now!

**Comment by Alakabon** [comment]
Did it work ? The suspense is killing me.

**Comment by Irithyl** [comment]
I will tell in a sec, I did the verify integrity thingy which takes ageeeees.

**Comment by Irithyl** [comment]
Deleted that file, did everything again, and got this error in testing:

2016-03-08 00:11:47.790 +00:00 [Error] The patch located in D:\Programs\Steam\steamapps\common\Pillars of Eternity\ie mod\Mods\IEMod.dll could not be loaded.
Patchwork.PatchDeclerationException: The patch did not have a PatchInfo class.
   at PatchworkLauncher.LaunchManager.Command_Direct_AddPatch(String path, Boolean isEnabled)
2016-03-08 00:11:47.810 +00:00 [Error] An error has occurred,
While trying to: Load a patch
Error type: A patch was invalid, incompatible, or caused an error. (PatchDeclerationException)
Internal message: The patch did not have a PatchInfo class.
Object(s) that failed: D:Programs...\Mods\IEMod.dll
.
.
.

The file goes on and on lol

**Comment by Irithyl** [comment]
The file that I deleted was this one: Assembly-CSharp.dll.pw.modified

EDIT: Added my log file.
[log.txt](https://github.com/GregRos/IEMod.pw/files/162379/log.txt)

**Comment by Alakabon** [comment]
That's the strangest thing...hold on, I'll do a fresh install see what happens

**Comment by tjayharvey** [comment]
The message still indicates to me that the patcher thinks it wants to use the wrong dll.

Try this:  Go into that directory and delete any file named iemod.dll. There should only be iemod.pw.dll.
Now run the launcher, go into Active Mods and make sure only iemod.pw.dll is there. Try patching with those settings.

**Comment by Irithyl** [comment]
Just one quick question, by patching you mean clicking the test button?

**Comment by Irithyl** [comment]
Oh wait! It's working now! I dont have a clue what I did differently, but I got this good test report now.

[log2.txt](https://github.com/GregRos/IEMod.pw/files/162386/log2.txt)

**Comment by Irithyl** [comment]
Thank you so much for the help guys and for all the hard work with iemod! You are the best!!!

**Comment by tjayharvey** [comment]
Issue seems resolved. Sorry for posting the wrong file originally.

**Comment by Irithyl** [comment]
No no, please don't apologize. When all seemed lost you guys picked up again the ie mod and saved  us all. Everything's good again :)
